site_name: 'Documentación EDD/LMSGI - Andy Pérez'

theme:
  name: 'material'
  favicon: recursos/apuntes.png
  logo: recursos/apuntes.png
  custom_dir: 'overrides'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.links
    - content.code.annotation
    - content.code.copy
  language: es
  palette:
    # Paleta para cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Cambiar a modo claro
    # Paleta para cambiar a modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/lightbulb-outline
        name: Cambiar a modo oscuro

extra_css:
  - 'overrides/extra.css'

nav:
  - Inicio: index.md

  - EDD:
    - Tema 1: 
      - Ejercicios: EDD/Tema1/Ejercicios.md
    - Tema 3: 
      - RSC y subversion: EDD/Tema3/RSC_Subversion.md
      - GIT: EDD/Tema3/GIT.md
      - Clonar GIT: EDD/Tema3/gitclonar.md
    - Tema 4:
      - JAVA: EDD/Tema4/java.md
      - ANT: EDD/Tema4/ant.md
      - MAVEN: EDD/Tema4/maven.md

  - LMSGI:
    - Tema 1: 
      - Apuntes: LMI/Tema1/Apuntes.md   
      - Ejercicios: LMI/Tema1/Ejercicios.md
    - Tema 2:
      - HTML:
        - Ejercicio 1: LMI/Tema2/HTML/Ejercicio1.html
        - Ejercicio 2: LMI/Tema2/HTML/Ejercicio2.html
        - Ejercicio 3: LMI/Tema2/HTML/Ejercicio3.html
        - Ejercicio 4: LMI/Tema2/HTML/Ejercicio4.html
        - Ejercicio 5: LMI/Tema2/HTML/Ejercicio5.html
        - Ejercicio 6: LMI/Tema2/HTML/Ejercicio6.html
        - Ejercicio 7: LMI/Tema2/HTML/Ejercicio7.html
        - Ejercicio 8: LMI/Tema2/HTML/Ejercicio8.html
        - Ejercicio 9: LMI/Tema2/HTML/Ejercicio9.html
        - Ejercicio 10: LMI/Tema2/HTML/Ejercicio10.html
        - Ejercicio 11: LMI/Tema2/HTML/Ejercicio11.html
        - Ejercicio 12: LMI/Tema2/HTML/Ejercicio12.html
        - Ejercicio 13: LMI/Tema2/HTML/Ejercicio13.html
        - Formulario: LMI/Tema2/HTML/Formulario.html
      - CSS:
        - Curriculum: LMI/Tema2/CSS/Curriculum.html
        - Horario: LMI/Tema2/CSS/Horario.html
    - Tema 3:
      - Ejercicios: LMI/Tema3/Ejercicios.md
