site_name: 'Documentación EDD/LMSGI - Andy Pérez'

theme:
  name: 'material'
  favicon: recursos/apuntes.png
  logo: recursos/apuntes.png
  custom_dir: 'overrides'
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.links
    - content.code.annotation
    - content.code.copy
  language: es
  palette:
    # Paleta para cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Cambiar a modo claro
    # Paleta para cambiar a modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/lightbulb-outline
        name: Cambiar a modo oscuro

plugins:
  - mkdocs_jarplantuml:
      plantuml_jar: plugins/plantuml-1.2025.0.jar
      output_format: png
      output_dir: diagrames

markdown_extensions:
  - admonition
  - pymdownx.details

extra_css:
  - extra.css

nav:
  - Inicio: index.md

  - EDD:
    - Apuntes:
      - Tema 1: EDD/Apuntes/ApuntesTema1.md
      - Tema 3: EDD/Apuntes/ApuntesTema3.md
    - Tema 1: 
      - Ejercicios: EDD/Tema1/Ejercicios.md
    - Tema 3: 
      - RSC y subversion: EDD/Tema3/RSC_Subversion.md
      - GIT: EDD/Tema3/GIT.md
      - Clonar GIT: EDD/Tema3/gitclonar.md
    - Tema 4:
      - JAVA: EDD/Tema4/java.md
      - ANT: EDD/Tema4/ant.md
      - MAVEN: EDD/Tema4/maven.md

  - LMSGI:
    - Tema 1: 
      - Apuntes: LMI/Tema1/Apuntes.md   
      - Ejercicios: LMI/Tema1/Ejercicios.md
    - Tema 3:
      - Ejercicios: LMI/Tema3/Ejercicios.md
