name: Install Graphviz

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update and install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install graphviz -y

      - name: Verify Graphviz installation
        run: dot -V
